theme = "bogster"


[editor]
color-modes = true
auto-pairs = true 
auto-save = true


[keys.normal]
"tab" = { c = [":config-open"]}
C-s = ":w" 
# "esc" = ["collapse_selection", ":w"]

[keys.select]
# "esc" = ["collapse_selection", "normal_mode", ":w"]

[keys.insert]
C-s = ":w" 
# "esc" = ["normal_mode", ":w"]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "position-percentage" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true


[editor.lsp]
enable=true
auto-signature-help=true
display-messages = true
